bots:
  proxy:
    image: "botica-bot-restest-proxy"
    replicas: 1

  telegram-frontend:
    image: "botica-bot-telegram-frontend"
    replicas: 1
    mount:
      - source: ".telegram-bot-data"
        target: "/app/.telegram-bot-data"
        createHostPath: true
    subscribe:
      - key: "telegram_bot"
        strategy: broadcast
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}

  generator:
    image: "botica-bot-restest-generator"
    mount:
      - source: "./resources"
        target: "/app/resources"
      - source: "./resources/config.properties"
        target: "/app/src/main/resources/config.properties" # hardcoded location in RESTest, will open issue
      - source: "./output"
        target: "/app/output"
        createHostPath: true
    lifecycle:
      type: proactive
      period: 60
    subscribe:
      - key: "generator_bots_advice"
        strategy: broadcast
    instances:
      generator-anapioficeandfire:
        environment:
          - USER_CONFIG_PATH=/app/resources/anapioficeandfire.com/user-config.properties
      generator-restcountries:
        environment:
          - USER_CONFIG_PATH=/app/resources/restcountries.com/user-config.properties
      generator-amadeus:
        environment:
          - USER_CONFIG_PATH=/app/resources/amadeus.com/user-config.properties
    environment:
      - PROXY_BOT_ID=proxy-1

  executor:
    image: "botica-bot-restest-executor"
    replicas: 5
    mount:
      - source: "./resources"
        target: "/app/resources"
      - source: "./resources/config.properties"
        target: "/app/src/main/resources/config.properties" # hardcoded location in RESTest, will open issue
      - source: "./output"
        target: "/app/output"
        createHostPath: true
    subscribe:
      - key: "executor_bots"
        strategy: distributed

  reporter:
    image: "botica-bot-restest-reporter"
    replicas: 2
    mount:
      - source: "./RESTest/allure"
        target: "/app/allure"
      - source: "./resources"
        target: "/app/resources"
      - source: "./resources/config.properties"
        target: "/app/src/main/resources/config.properties" # hardcoded location in RESTest, will open issue
      - source: "./output"
        target: "/app/output"
        createHostPath: true
    subscribe:
      - key: "reporter_bots"
        strategy: distributed
