broker:
  type: rabbitmq
  username: "username"
  password: "password"
  port: 5672

bots:
  generator:
    image: "botica-bot-restest-generator"
    mount:
      - source: "./resources"
        target: "/app/resources"
      - source: "./resources/config.properties"
        target: "/app/src/main/resources/config.properties" # hardcoded location in RESTest, will open issue
      - source: "./output"
        target: "/app/output"
        createHostPath: true
    publish:
      key: "test_execution"
      order: "execute_test_cases"
    lifecycle:
      type: proactive
      initialDelay: 0
      period: 60
    instances:
      generator-anapioficeandfire:
        environment:
          - USER_CONFIG_PATH=/app/resources/anapioficeandfire.com/user-config.properties
      generator-restcountries:
        environment:
          - USER_CONFIG_PATH=/app/resources/restcountries.com/user-config.properties
#      generator-amadeus:
#        environment:
#          - USER_CONFIG_PATH=/app/resources/amadeus.com/user-config.properties

  executor:
    image: "botica-bot-restest-executor"
    mount:
      - source: "./resources"
        target: "/app/resources"
      - source: "./resources/config.properties"
        target: "/app/src/main/resources/config.properties" # hardcoded location in RESTest, will open issue
      - source: "./output"
        target: "/app/output"
        createHostPath: true
    publish:
      key: "test_reporting"
      order: "generate_test_report"
    subscribe:
      - key: "test_execution"
        strategy: distributed
    lifecycle:
      type: reactive
      order: "execute_test_cases"
    instances:
      executor-1: { }
      executor-2: { }
      executor-3: { }

  reporter:
    image: "botica-bot-restest-reporter"
    mount:
      - source: "./RESTest/allure"
        target: "/app/allure"
      - source: "./resources"
        target: "/app/resources"
      - source: "./resources/config.properties"
        target: "/app/src/main/resources/config.properties" # hardcoded location in RESTest, will open issue
      - source: "./output"
        target: "/app/output"
        createHostPath: true
    subscribe:
      - key: "test_reporting"
        strategy: distributed
    lifecycle:
      type: reactive
      order: "generate_test_report"
    instances:
      reporter-1: { }
      reporter-2: { }
