broker:
  type: rabbitmq
  username: "username"
  password: "password"
  port: 5672

bots:
  generator:
    image: "botica-bot-restest-generator"
    mount:
      - source: "./src"
        target: "/app/src"
      - source: "./target"
        target: "/app/target"
        createHostPath: true
    publish:
      key: "test_execution"
      order: "execute_test_cases"
    lifecycle:
      type: proactive
      period: 100
    instances:
      generator-marvel-r-art-custom:
        lifecycle:
          type: proactive
          period: 345
        environment:
          - USER_CONFIG_PATH=src/test/resources/taas_eval/Marvel/r_art_custom/props.properties
      generator-marvel-r-ft:
        lifecycle:
          type: proactive
          period: 345
        environment:
          - USER_CONFIG_PATH=src/test/resources/taas_eval/Marvel/r_ft_/props.properties
      generator-marvel-r-rt-custom:
        lifecycle:
          type: proactive
          period: 345
        environment:
          - USER_CONFIG_PATH=src/test/resources/taas_eval/Marvel/r_rt_custom/props.properties
      generator-marvel-r-rt-perturbation:
        lifecycle:
          type: proactive
          period: 345
        environment:
          - USER_CONFIG_PATH=src/test/resources/taas_eval/Marvel/r_rt_perturbation/props.properties
#      generator-marvel-r-rt-stateful
#        environment:
#          - USER_CONFIG_PATH=src/test/resources/taas_eval/Marvel/r_rt_stateful/props.properties

      generator-stripe-r-cbt-custom:
        lifecycle:
          type: proactive
          period: 100
        environment:
          - USER_CONFIG_PATH=src/test/resources/taas_eval/Stripe_Products/r_cbt_custom/props.properties
      generator-stripe-rw-art-custom:
        lifecycle:
          type: proactive
          period: 100
        environment:
          - USER_CONFIG_PATH=src/test/resources/taas_eval/Stripe_Products/rw_art_custom/props.properties
      generator-stripe-rw-cbt-custom:
        lifecycle:
          type: proactive
          period: 100
        environment:
          - USER_CONFIG_PATH=src/test/resources/taas_eval/Stripe_Products/rw_cbt_custom/props.properties
      generator-stripe-rw-cbt-perturbation:
        lifecycle:
          type: proactive
          period: 100
        environment:
          - USER_CONFIG_PATH=src/test/resources/taas_eval/Stripe_Products/rw_cbt_perturbation/props.properties
      generator-stripe-rw-cbt-stateful:
        lifecycle:
          type: proactive
          period: 100
        environment:
          - USER_CONFIG_PATH=src/test/resources/taas_eval/Stripe_Products/rw_cbt_stateful/props.properties
      generator-stripe-rw-ft:
        lifecycle:
          type: proactive
          period: 100
        environment:
          - USER_CONFIG_PATH=src/test/resources/taas_eval/Stripe_Products/rw_ft_/props.properties
      generator-stripe-rw-rt-custom:
        lifecycle:
          type: proactive
          period: 100
        environment:
          - USER_CONFIG_PATH=src/test/resources/taas_eval/Stripe_Products/rw_rt_custom/props.properties

      generator-omdb-r-cbt-custom:
        lifecycle:
          type: proactive
          period: 259
        environment:
          - USER_CONFIG_PATH=src/test/resources/taas_eval/OMDb/r_cbt_custom/props.properties
      generator-omdb-r-cbt-perturbation:
        lifecycle:
          type: proactive
          period: 259
        environment:
          - USER_CONFIG_PATH=src/test/resources/taas_eval/OMDb/r_cbt_perturbation/props.properties
      generator-omdb-r-cbt-semantic:
        lifecycle:
          type: proactive
          period: 259
        environment:
          - USER_CONFIG_PATH=src/test/resources/taas_eval/OMDb/r_cbt_semantic/props.properties
      generator-omdb-r-cbt-stateful:
        lifecycle:
          type: proactive
          period: 259
        environment:
          - USER_CONFIG_PATH=src/test/resources/taas_eval/OMDb/r_cbt_stateful/props.properties
      generator-omdb-r-ft:
        lifecycle:
          type: proactive
          period: 259
        environment:
          - USER_CONFIG_PATH=src/test/resources/taas_eval/OMDb/r_ft_/props.properties
      generator-omdb-r-rt-custom:
        lifecycle:
          type: proactive
          period: 259
        environment:
          - USER_CONFIG_PATH=src/test/resources/taas_eval/OMDb/r_rt_custom/props.properties

      generator-restcountries-r-ft:
        lifecycle:
          type: proactive
          period: 345
        environment:
          - USER_CONFIG_PATH=src/test/resources/taas_eval/Restcountries/r_ft_/props.properties
      generator-restcountries-r-rt-custom:
        lifecycle:
          type: proactive
          period: 345
        environment:
          - USER_CONFIG_PATH=src/test/resources/taas_eval/Restcountries/r_rt_custom/props.properties
      generator-restcountries-r-rt-perturbation:
        lifecycle:
          type: proactive
          period: 345
        environment:
          - USER_CONFIG_PATH=src/test/resources/taas_eval/Restcountries/r_rt_perturbation/props.properties
      generator-restcountries-r-rt-semantic:
        lifecycle:
          type: proactive
          period: 345
        environment:
          - USER_CONFIG_PATH=src/test/resources/taas_eval/Restcountries/r_rt_semantic/props.properties
      generator-restcountries-r-rt-stateful:
        lifecycle:
          type: proactive
          period: 345
        environment:
          - USER_CONFIG_PATH=src/test/resources/taas_eval/Restcountries/r_rt_stateful/props.properties

  executor:
    image: "botica-bot-restest-executor"
    mount:
      - source: "./src"
        target: "/app/src"
      - source: "./target"
        target: "/app/target"
        createHostPath: true
    publish:
      key: "test_reporting"
      order: "generate_test_report"
    subscribe:
      - key: "test_execution"
        strategy: distributed
    lifecycle:
      type: reactive
      order: "execute_test_cases"
    instances:
      executor-1: { }
      executor-2: { }
      executor-3: { }
      executor-4: { }
      executor-5: { }
      executor-6: { }

  reporter:
    image: "botica-bot-restest-reporter"
    mount:
      - source: "./RESTest/allure"
        target: "/app/allure"
      - source: "./src"
        target: "/app/src"
      - source: "./target"
        target: "/app/target"
        createHostPath: true
    subscribe:
      - key: "test_reporting"
        strategy: distributed
    lifecycle:
      type: reactive
      order: "generate_test_report"
    instances:
      reporter-1: { }
      reporter-2: { }
